// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:9a7a66a8-e5f8-4959-9313-3080cf05f54f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_FxmCV9thH",
    "aws_user_pools_web_client_id": "6gv8o7hqjvmkti10o3d2juvp9d",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://qodqphayfveerhcg4d7hmztvj4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-sunxbq3c5vhdla7qg7ukbteflm"
};


export default awsmobile;
